### ISSUE TITLE
Cannot download dataset

### ISSUE THREAD

**Issue by MaxGodTier** [yasaminjafarian/HDNet_TikTok#1]
It keeps saying "Sorry, you can't view or download this file at this time. Too many users have viewed or downloaded this file recently... etc.", can we have more alternative links/mirrors or a torrent please? Thank you very much for sharing this.

**Comment by yasaminjafarian** [comment]
Hi. Thanks a lot for mentioning that. Could you check again? https://www.yasamin.page/hdnet_tiktok
I temporarily changed the link till we upload it in a new cloud.

**Comment by MaxGodTier** [comment]
It's working now, thank you so much!

**Comment by Twizwei** [comment]
Hi there @yasaminjafarian, sorry I met the same issue. Could you please check it again? Thanks!

**Comment by yasaminjafarian** [comment]
Hi. Please send me an email to **yasamin@umn.edu** so that I can share the drive with you.
