### ISSUE TITLE
Pretrained model without Rendered people

### ISSUE THREAD

**Issue by jseobyun** [yasaminjafarian/HDNet_TikTok#10]
Hello, thank you for sharing this amazing work. 

HDNet (trained by 34,000 RenderedPeople images and 100,000 Tiktok images) performance is very impressive compared to previous works :)

After reading the paper, I became curious about the performance of HDNet trained without RenderedPeople and with fewer RenderedPeople

Do you have pre-trained HDNet of those cases? or the results?

**Comment by yasaminjafarian** [comment]
Hi. Thanks a lot for your message. This work is trained in a semi-supervised framework therefore having the RenderPeople data is important. We unfortunately don't have the pre-trained model for a smaller amount of RenderPeople.

**Comment by jseobyun** [comment]
Thanks!
