### ISSUE TITLE
Eq (4)

### ISSUE THREAD

**Issue by Mathilda88** [yasaminjafarian/HDNet_TikTok#11]
Hi  Yasamin,

Thanks for sharing your great work. May you please point me out to the line by which you've implements Eq. (4). 

Thanks,

**Comment by yasaminjafarian** [comment]
Hi,

Thanks a lot for your interest. It is implemented in this [function](https://github.com/yasaminjafarian/HDNet_TikTok/blob/main/training/training_code/utils/Geometry_MB.py#L94).

**Comment by Mathilda88** [comment]
Thanks, extraordinarily good!

**Comment by yasaminjafarian** [comment]
Thanks!
