### ISSUE TITLE
Cudnn failed to initialize

### ISSUE THREAD

**Issue by TContamin** [yasaminjafarian/HDNet_TikTok#12]
Hello, thanks for sharing this code.

I tried to run the demo but I failed building the environment. I use the docker as tensorflow doesn't match but I still have some issues. I used python 3.5 (because of the docker), Cuda 11.0 and Cudnn 10.2.

It is the first time I use docker and Cudnn and I'm not sure how to proceed to install the versions of CUDA and Cudnn you used to run the project.

The error message is the following one.

```WARNING: Logging before flag parsing goes to stderr.
W0816 09:34:40.781714 140426061592320 deprecation_wrapper.py:119] From HDNet_Inference.py:15: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0816 09:34:40.781880 140426061592320 deprecation_wrapper.py:119] From HDNet_Inference.py:15: The name tf.logging.ERROR is deprecated. Please use tf.compat.v1.logging.ERROR instead.

------------------------------
Hourglass Architecture
------------------------------
------------------------------
Hourglass Architecture
------------------------------
Model DR restored.
Model NP restored.
Processing file:  0043
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node hourglass_normal_prediction/conv1/Conv2D}}]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node hourglass_normal_prediction/conv1/Conv2D}}]]
	 [[hourglass_normal_prediction/conv18/BiasAdd/_177]]
0 successful operations.
0 derived errors ignored.

Thanks in advance.

**Comment by yasaminjafarian** [comment]
Hi. If you want to use docker, you may want to get the tensorflow-docker image from [here](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_19.03.html#rel_19.03).

If you already have docker installed you can just follow and run [this](https://github.com/yasaminjafarian/HDNet_TikTok#:~:text=In%20case%20there,r%20requirements.txt)  
Note that you don't need to do anything else if you use this environment. Just install requirements.txt after that.

If you don't want to use docker, the code is tested under this [cuda, cudnn and tensorflow](https://github.com/yasaminjafarian/HDNet_TikTok#:~:text=(This%20code%20is%20tested%20with%20tensorflow-gpu%201.14.0%2C%20Python%203.7.4%2C%20CUDA%2010%20(version%2010.0.130)%20and%20cuDNN%207%20(version%207.4.2).)) that is mentioned. 

Please read the readme file carefully to follow the installation correctly.

**Comment by TContamin** [comment]
Thanks for your answer.

I read it carefully and I tried to use HDNet with docker, the error appears while I use docker. I though that I had to install Cudnn in docker because of the error bellow and that's what I did but it is still not working, the error is exactly the same. (Obviously I installed the requirements in docker)

```(0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.```

**Comment by yasaminjafarian** [comment]
Thanks for reaching out.
This docker image already has the cudnn and cuda installed. You can see the available libraries coming with this container [here](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html#:~:text=19.03-,19.02,-19.01). This is an example of how the code runs in the container:
![image](https://user-images.githubusercontent.com/50026215/129828251-5d0048d7-2216-491b-b014-7d7ee3a7f57e.png)
However, If there are still problems with the installation, I have added the [google colab notebook](https://github.com/yasaminjafarian/HDNet_TikTok#inference-demo-on-google-colab) as well that you can check out.

**Comment by yasaminjafarian** [comment]
As there are no other updates on this issue, it will be closed.
