### ISSUE TITLE
Cannot download pretrained model

### ISSUE THREAD

**Issue by qianlim** [yasaminjafarian/HDNet_TikTok#14]
Hi! I'm trying to download the pretrained model either via wget (provided command in the README) or directly on the google drive webpage, both failed. 

wget reports:
![image](https://user-images.githubusercontent.com/22825578/134392007-7830cda4-8022-460f-8b34-03616faffde2.png)

On the webpage Google Drive says: 
![image](https://user-images.githubusercontent.com/22825578/134391944-cce8f2ac-7c3f-4231-87be-1b02d81d40f6.png)

Could you help out here? Thanks.

**Comment by qianlim** [comment]
Now it seems to be downloadable again. Sorry for spamming.

**Comment by yasaminjafarian** [comment]
Hi. Thanks a lot for the comment. I also added [a few more options](https://github.com/yasaminjafarian/HDNet_TikTok#run-the-demo) in the readme file to download the weights in case the links are broken again.
