### ISSUE TITLE
TikTok Data DensePose Image Mistakes?

### ISSUE THREAD

**Issue by terteros** [yasaminjafarian/HDNet_TikTok#17]
Hi again, we realized that in some of the densepose results, it seems like two dp results are stitched together. I wonder if you perhaps combined all the densepose detections for a single image. Is this a preprocessing mistake or intentional? Because I think it results in detrimental densepose inputs to the model. 
We have a script to generate densepose results using [detectron2 densepose implementation](https://github.com/facebookresearch/detectron2/tree/main/projects/DensePose) and best DensePose model with [resnet101 bakcbone and DeepLabV3 head](https://github.com/facebookresearch/detectron2/blob/main/projects/DensePose/doc/DENSEPOSE_IUV.md#-improved-baselines-deeplabv3-head). The results are strikingly better as you can see from the below example:
![tiktok_dp_issue](https://user-images.githubusercontent.com/14004171/137330649-6f53366e-09b3-42d1-9025-6a3adf173c05.png)

I wonder if the model would improve if we train with these densepose inputs, instead of the ones provided in TikTok dataset.

**Comment by yasaminjafarian** [comment]
Hi. Yes, the better DensePose you have the better reconstruction you will get.
