### ISSUE TITLE
Correspondence of Densepose

### ISSUE THREAD

**Issue by yf1019** [yasaminjafarian/HDNet_TikTok#18]
Hi Yasamin, very awesome work!

I'm trying to train this work on my custom dataset. I found that the correspondence *.txts given in the training example are not simply defined by the UV ordinates obtained from the Densepose. If I directly construct correspondence between pixels with the same UV ordinates, it will lead to a very sparse mapping which is not as good as your pre-processed data. So I'd like to ask how did you construct the correspondence mapping between two densepose results? 

Many Thanks!

**Comment by yasaminjafarian** [comment]
Hi. Thanks a lot. I use [knnsearch](https://www.mathworks.com/help/stats/knnsearch.html) to get the closest UV on the other image. If the distance is less than 7 I accept it as the correspondence.

**Comment by yf1019** [comment]
Got it. Thanks a lot!

> Hi. Thanks a lot. I use [knnsearch](https://www.mathworks.com/help/stats/knnsearch.html) to get the closest UV on the other image. If the distance is less than 7 I accept it as the correspondence.
