### ISSUE TITLE
List DensePose as a requirement.

### ISSUE THREAD

**Issue by ExponentialML** [yasaminjafarian/HDNet_TikTok#2]
It seems that DensePose is required, but it's discreetly mentioned in the inference section. This repository **requires** DensePose, therefore it should be listed under requirements.

**Comment by yasaminjafarian** [comment]
Thanks a lot for your message. The DensePose is not required to be installed on your computer to run this code. You just need to have the IUV maps from it as an input (For example TikTok dataset already provides those IUV maps). The inference with the option of omitting the densepose as input will probably be added soon as well.
