### ISSUE TITLE
Training with batch_size > 1 is not possible

### ISSUE THREAD

**Issue by terteros** [yasaminjafarian/HDNet_TikTok#20]
When I change the variable `BATCH_SIZE` in [training_HDNet.py](https://github.com/yasaminjafarian/HDNet_TikTok/blob/452576d38c2d14c2ca241b2b9322a94eb682881f/training/training_code/training_HDNet.py#L30), it raises an error in [Depth2Points3D_transformed_vector](https://github.com/yasaminjafarian/HDNet_TikTok/blob/452576d38c2d14c2ca241b2b9322a94eb682881f/training/training_code/utils/denspose_transform_functions.py#L70). The issue is there is an another `batch_size` parameter in the line 51 of the same function. 
Even if I set it to be the same as `BATCH_SIZE`, the training wouldn't work as intended because, tiktok batches are discarded in [transform_depth_PCs_dp_based2](https://github.com/yasaminjafarian/HDNet_TikTok/blob/452576d38c2d14c2ca241b2b9322a94eb682881f/training/training_code/utils/denspose_transform_functions.py#L133). Since each TikTok sample will have different number of correspondences, I guess the best solution is iterating over batches inside `transform_depth_PCs_dp_based2`.

**Comment by yasaminjafarian** [comment]
Yes this implementation only supports batch 1 as mentioned [here](https://github.com/yasaminjafarian/HDNet_TikTok/tree/main/training#:~:text=Note%20that%20this%20can%20be%20trained%20with%20batch%20size%201%20only).
For the easier implementation the number of correspondences is fixed to 25000 as mentioned [here](https://github.com/yasaminjafarian/HDNet_TikTok/blob/main/training/training_code/training_HDNet.py#L62).

**Comment by lql1233** [comment]
> 当我更改[training_HDNet.py](https://github.com/yasaminjafarian/HDNet_TikTok/blob/452576d38c2d14c2ca241b2b9322a94eb682881f/training/training_code/training_HDNet.py#L30)`BATCH_SIZE`中的变量时，它会在[Depth2Points3D_transformed_vector](https://github.com/yasaminjafarian/HDNet_TikTok/blob/452576d38c2d14c2ca241b2b9322a94eb682881f/training/training_code/utils/denspose_transform_functions.py#L70)中引发错误。问题是在同一函数的第 51 行中还有另一个参数。 即使我将其设置为与 相同，训练也不会按预期进行，因为在[transform_depth_PCs_dp_based2](https://github.com/yasaminjafarian/HDNet_TikTok/blob/452576d38c2d14c2ca241b2b9322a94eb682881f/training/training_code/utils/denspose_transform_functions.py#L133)中丢弃了 tiktok 批次。由于每个 TikTok 样本将有不同数量的对应关系，我想最好的解决方案是迭代里面的批次。[](https://github.com/yasaminjafarian/HDNet_TikTok/blob/452576d38c2d14c2ca241b2b9322a94eb682881f/training/training_code/training_HDNet.py#L30)[](https://github.com/yasaminjafarian/HDNet_TikTok/blob/452576d38c2d14c2ca241b2b9322a94eb682881f/training/training_code/utils/denspose_transform_functions.py#L70)`batch_size``BATCH_SIZE`[](https://github.com/yasaminjafarian/HDNet_TikTok/blob/452576d38c2d14c2ca241b2b9322a94eb682881f/training/training_code/utils/denspose_transform_functions.py#L133)`transform_depth_PCs_dp_based2`

I also have the same problem, do you have any solution for this problem?

**Comment by lql1233** [comment]
> When I change the variable `BATCH_SIZE` in [training_HDNet.py](https://github.com/yasaminjafarian/HDNet_TikTok/blob/452576d38c2d14c2ca241b2b9322a94eb682881f/training/training_code/training_HDNet.py#L30), it raises an error in [Depth2Points3D_transformed_vector](https://github.com/yasaminjafarian/HDNet_TikTok/blob/452576d38c2d14c2ca241b2b9322a94eb682881f/training/training_code/utils/denspose_transform_functions.py#L70). The issue is there is an another `batch_size` parameter in the line 51 of the same function. Even if I set it to be the same as `BATCH_SIZE`, the training wouldn't work as intended because, tiktok batches are discarded in [transform_depth_PCs_dp_based2](https://github.com/yasaminjafarian/HDNet_TikTok/blob/452576d38c2d14c2ca241b2b9322a94eb682881f/training/training_code/utils/denspose_transform_functions.py#L133). Since each TikTok sample will have different number of correspondences, I guess the best solution is iterating over batches inside `transform_depth_PCs_dp_based2`.

I also have the same problem, do you have any solution for this problem?
