### ISSUE TITLE
Inference Demo

### ISSUE THREAD

**Issue by lql1233** [yasaminjafarian/HDNet_TikTok#23]
Does the inference demo just use the tang datasets (pre-training model )instead of the HDNet model，So the reasoning effect is not very good？

**Comment by yasaminjafarian** [comment]
The pre-trained model provided is trained with RenderPeople data for the HDNet. Tang dataset is not used in our training.

**Comment by lql1233** [comment]
> 提供的预训练模型使用 HDNet 的 RenderPeople 数据进行训练。我们的训练中不使用 Tang 数据集。

Thank you for your prompt reply. I would like to ask about how to generate preprocessing files for unlabeled data during training? I have downloaded the complete Tiktok dataset, but the preprocessed files (such as corr_mat.txt in the correspondences folder, similar to 0017634_0017637_i_r1_c1_r2_c2.txt and 0017634_0017637_i_limit.txt,), can provide the complete Tiktok dataset related training files Or preprocess the data code?

**Comment by yasaminjafarian** [comment]
You can see the information of these files in training data [here](https://github.com/yasaminjafarian/HDNet_TikTok/tree/main/training#:~:text=You%20need%20to%20do%20some%20pre-processing%20to%20use%20unlabeled%20data%20for%20training%3A). To get the *_i_r1_c1_r2_c2.txt I basically use nearest neighbours on the UV coordinate of each body part between the two frames to find the correspondences. Maybe in future we provide the training data or the data generation code but for now you can just use nearest neighbors to get the correspondences between two frames.

**Comment by lql1233** [comment]
Thank you for your patience, the work is great！
