### ISSUE TITLE
Demo and Pretrained Weights

### ISSUE THREAD

**Issue by terteros** [yasaminjafarian/HDNet_TikTok#24]
The models provided for inference and training seem to be the same. Is the model trained on RenderPeople and TikTok dataset or only RenderPeople?

**Comment by yasaminjafarian** [comment]
[HDNet model](https://github.com/yasaminjafarian/HDNet_TikTok/blob/main/HDNet_Inference.py#L32): RenderPeople and TikTok dataset 
[Normal Estimator model](https://github.com/yasaminjafarian/HDNet_TikTok/blob/main/HDNet_Inference.py#L34): only RenderPeople
