### ISSUE TITLE
UV wrap configuration

### ISSUE THREAD

**Issue by bobluoluo** [yasaminjafarian/HDNet_TikTok#26]
Tremendous work! Best paper in 2021. The output from Densepose is different from the one in the example. How is the uv 0-1 mapped to RGB? What configuration do you use when using Densepose? Also, is it really uv map or vertex map on the SMPL model I should be using? The uv map from this repo and the one genereated from Densepose by myself  look different.

original
![0043_img](https://user-images.githubusercontent.com/56043227/149006108-d615ecd1-f9b3-4674-9fbc-c34dafbab5a9.png)
Yours
![0043_dp](https://user-images.githubusercontent.com/56043227/149005536-55ac1a68-73b2-4c53-a08e-e9361c85df9a.png)
Mine
![uv 0001](https://user-images.githubusercontent.com/56043227/149006245-60e62d44-274a-4f74-98d7-3c574d351ae9.png)

**Comment by yasaminjafarian** [comment]
Thanks for the message. different weight of densepose has different results.
The visualization you show is IUV the visualization we have in this example is VUI. so you may just want to change the order of channels. We use densepose, not SMPL.

**Comment by umariqb** [comment]
Hi Yasamin,

Which color map do you use? DensePose in detectron uses [cv::COLORMAP_PARULA] and swapping the channels doesn't make it consistent with what you have. Any idea?

![dp 0001](https://user-images.githubusercontent.com/5772474/197384085-80a595bf-4fdb-4bcc-b4fd-10f5a61ef721.png)

**Comment by zwplus** [comment]
You can refer to this issue:https://github.com/facebookresearch/detectron2/issues/4554, I used his method to solve the problem.
