### ISSUE TITLE
Intrinsics 

### ISSUE THREAD

**Issue by bobluoluo** [yasaminjafarian/HDNet_TikTok#27]
The training data might could have different Ks, which is dependent on capture devices, cameras on cell phones. It seems to me that mean multiple K matrices( maybe even distortion coeffs) would be hard-coded to the network in the process. How does it affect the result? What are your thoughts about decoupling the intrinsics from this en/decoding network? Can intrinsics be provided when inference?

**Comment by yasaminjafarian** [comment]
We use a fixed K matrix. See [here](https://github.com/yasaminjafarian/HDNet_TikTok/blob/main/utils.py#L90)
If your task should be aware of the camera parameters, I think decoupling should help.
