### ISSUE TITLE
code for rendering 'RenderPeople dataset' ? 

### ISSUE THREAD

**Issue by wangzheallen** [yasaminjafarian/HDNet_TikTok#3]
Hi Yasamin,

Great to know your wonderful work! Will you release the code for  rendering 'RenderPeople dataset'  with ' ray tracing algorithm to compute the ground truth depth and render the human textured model'?

Thanks!

**Comment by yasaminjafarian** [comment]
Hi,

Thanks a lot. I used Blender API for rendering the RenderPeople dataset. I might add the codes in another repository later but the following repositories about Blender can be useful for this task:
https://github.com/yuki-koyama/blender-cli-rendering
https://github.com/weiaicunzai/blender_shapenet_render/blob/master/render_depth.py
