### ISSUE TITLE
about making image pairs

### ISSUE THREAD

**Issue by pshlego** [yasaminjafarian/HDNet_TikTok#33]
There was a problem in the process of making an image pair. According to the paper, "At each time instant, we make five image pairs by randomly selecting time instances that have the UV coordinates of at least five common visible body parts while each contains more than 50 overlapping UV coordinates." Does "overlapping UV coordinates" here mean that the exact same number of UV points is more than 50? all just similar points.

**Comment by yasaminjafarian** [comment]
just similar. if the distance between two UV is < the then we consider them a pair.
