### ISSUE TITLE
Evaluation datasets

### ISSUE THREAD

**Issue by chenhd1112** [yasaminjafarian/HDNet_TikTok#35]
Hello, author, I would like to know how the dataset (Vlasic et al.dataset, THuman2.0 dataset) you are evluating, how to perform ray tracing from mesh to depth map, can you provide relevant code or links or  related method implementation details.

**Comment by yasaminjafarian** [comment]
Hi. I extract the depth channel using Blender python API. But you can also use [pifuhd](https://github.com/facebookresearch/pifuhd/blob/main/apps/render_turntable.py) visualization code and get the z channel (z = renderer.get_z_value())
