### ISSUE TITLE
How to generate new view synthesis?

### ISSUE THREAD

**Issue by chenerg** [yasaminjafarian/HDNet_TikTok#6]
I'm interested in the new view video generated with the estimated depth, would you please share some methods to do this. Again, your work is really amazing!

**Comment by yasaminjafarian** [comment]
Thanks a lot for your comment. The MATLAB visualization code for this aim is now added to the [repository](https://github.com/yasaminjafarian/HDNet_TikTok#matlab-visualization).

**Comment by chenerg** [comment]
Thank you very much for your code. Congratulations on your paper being the best paper candidate！

**Comment by yasaminjafarian** [comment]
Thanks a lot!
