### ISSUE TITLE
Question regarding obtaining the foreground mask

### ISSUE THREAD

**Issue by YoungJoongUNC** [yasaminjafarian/HDNet_TikTok#7]
Hello!
I would like to first appreciate sharing your great work! It is a very impressive and wonderful work! :)

May I ask which method is used for extracting the foreground mask?

Thank you!

**Comment by yasaminjafarian** [comment]
Hi,

Thanks a lot for your message. We used [remove.bg](https://www.remove.bg/) for extracting the foreground as it gave us the most accurate results.
