### ISSUE TITLE
CUDA 11

### ISSUE THREAD

**Issue by gexahedron** [yasaminjafarian/HDNet_TikTok#8]
Hi! Is it possible to run your code on machine with CUDA 11? I get this error:

tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation hourglass_stack_fused_depth_prediction/conv1/weights/Initializer/truncated_normal/TruncatedNormal: Could not satisfy explicit device specification '' because the node {{colocation_node hourglass_stack_fused_depth_prediction/conv1/weights/Initializer/truncated_normal/TruncatedNormal}} was colocated with a group of nodes that required incompatible device '/device:GPU:0'. All available devices [/job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0].

and I suspect that it's connected to difference in CUDA version with the version mentioned in README.

**Comment by yasaminjafarian** [comment]
Hi. Thanks for your message. I have not tried CUDA 11 but it is possible to get error with another version of cuda for some specific functions.
