### ISSUE TITLE
Weird results

### ISSUE THREAD

**Issue by gexahedron** [yasaminjafarian/HDNet_TikTok#9]
Hi!

I've managed to run your code in the docker image that you provided. However, I get a very weird output on your default image:

<img width="981" alt="Screenshot 2021-06-24 at 22 11 05" src="https://user-images.githubusercontent.com/3427698/123326282-56243e00-d539-11eb-8b45-2bbe56d16583.png">

Do you know, what could be the problem?

Also, the running time was 22 minutes for a single 256x256 image, is it expected to run so slow?

**Comment by yasaminjafarian** [comment]
Hi. Thanks a lot for your message. It shouldn't take that long. It will take around a few seconds to read the weights and write the predictions. The these results are wrong. make sure that you have the weights downloaded and stored correctly.

**Comment by XiminLin** [comment]
Hi, I am also getting this result when running in the docker environment. @gexahedron Have you solved the problem? 
This is the folder structure. Thanks.

```
...
├── HDNet_Inference.py
├── hourglass_net_depth.py
├── hourglass_net_normal.py
├── model
│   ├── depth_prediction
│   │   └── model_1920000
│   │       ├── checkpoint
│   │       ├── model_1920000.ckpt.data-00000-of-00001
│   │       ├── model_1920000.ckpt.index
│   │       └── model_1920000.ckpt.meta
│   └── normal_prediction
│       └── model_1710000
│           ├── checkpoint
│           ├── model_1710000.ckpt.data-00000-of-00001
│           ├── model_1710000.ckpt.index
│           └── model_1710000.ckpt.meta
...
```

**Comment by SangHunHan92** [comment]
I am also getting this result, too
How to solve it ?

**Comment by SangHunHan92** [comment]
> 

Solved.
This is a problem that occurs when the cuda version outside the docker container is 11 or higher. Setting the cuda version to 10.x both outside and inside the container works fine.
